# -*- coding: utf-8 -*-
"""Webscrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-kOT4m1bjSMW77EKuYeWHG9E-9Lxw66G

Inicio com os imports
"""

from lxml import html
import requests
import pandas as pd
import dateutil.parser

"""Busco a página e defino na variavel "webpage""""

webpage = requests.get('https://www.nytimes.com/interactive/2017/06/23/opinion/trumps-lies.html')

"""Com a variavel "webpage", dou split nas informações"""

result = html.fromstring(webpage.content)

date1 = result.xpath('//span[@class="short-desc"]/strong/text()')
date=[]

for i in date1: 
    i = dateutil.parser.parse(i.strip('\xa0') + ' 2017')
    date.append(i)

lie = result.xpath('//span[@class="short-desc"]/text()')
lie = [x.strip('(') for x in lie]

explanation = result.xpath('//span[@class="short-truth"]/a/text()')
link = result.xpath('//span[@class="short-truth"]/a/@href')

"""Com as listas, monto um dataframe"""

df = {'Date':date,'Lie':lie,'Explanation':explanation,'Link':link}
df = pd.DataFrame(df)

"""Com o dataframe posso gerar o arquivo csv"""

df.to_csv('mentiras_trump.csv')

"""Tambem posso mostrar em tela o resultado do dataframe"""

df